# Generated by Django 3.0.6 on 2020-06-04 12:56

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs/', verbose_name='File')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='pdfs/covers/')),
                ('username', models.CharField(max_length=300, verbose_name='user name')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=200, verbose_name='The title of your event')),
                ('day', models.DateField(default=datetime.datetime(2020, 6, 4, 12, 56, 53, 700651, tzinfo=utc), verbose_name='Day of the event')),
                ('start_time', models.TimeField(verbose_name='Starting time')),
                ('end_time', models.TimeField(verbose_name='Final time')),
                ('notes', models.TextField(verbose_name='Textual notes')),
                ('username', models.CharField(max_length=300, verbose_name='user name')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=300, verbose_name='note tag')),
                ('note_title', models.CharField(max_length=200, verbose_name='the title of a note')),
                ('note_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('public_date', models.DateTimeField(default=datetime.datetime(2020, 6, 4, 12, 56, 53, 700033, tzinfo=utc), verbose_name='The publication date')),
                ('username', models.CharField(max_length=300, verbose_name='user name')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
